server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-db-dev?createDatabaseIfNotExist=true&useUnicode=true&amp&characterEncoding=utf-8&autoReconnect=true
    username: movie-user
    password: movie-pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
      generate-ddl: true
    

  info:
    application:
      name: movie-service
      description: Movie Service for Movies Application
      version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info,health,trace,metrics,serviceregistry
  info:
    env:
      enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/